blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'

urlpatterns = [
    path('', views.post_list, name='post_list'),
    path('<int:year>/<int:month>/<int:day>/<slug:post>/', views.post_detail, name='post_detail'),
    path('<int:post_id>/share/', views.post_share, name='post_share'),
    path('<int:post_id>/comment/', views.post_comment, name='post_comment'),
    path('tag/<str:tag_slug>/', views.post_list, name='post_list_by_tag'),
    path('search/', views.post_search, name='post_search'),
]

mysite/urls.py
from django.contrib import admin
from django.urls import path, re_path
from django.conf.urls import include
from blog.sitemaps import PostSitemap
from django.contrib.sitemaps.views import sitemap
from django.conf import settings
from django.conf.urls.static import static

sitemaps = {
    'posts': PostSitemap,
}

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls', namespace='blog')),
    path('sitemap.xml', sitemap, {'sitemaps': sitemaps}, name='django.contrib.sitemaps.views.sitemap'),
    path("accounts/", include("accounts.urls")),
    path('accounts/', include('django.contrib.auth.urls')),
    re_path(r'^oauth/', include('social_django.urls', namespace='social')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/blog/post/includes/comment_form.html
<form action="{% url 'blog:post_comment' post.id %}" method="post">
    {% csrf_token %}
    <div class="row">
        {% if user.is_authenticated %}
            <h3>Add a new comment, {{ user.username }}</h3>
            <div class="mt-2">
                {{ form.body }}
                <br>
                <input type="submit" class="btn btn-primary mb-3 mt-2" value="Add comment">
            </div>
        {% else %}
            <h3><a href="{% url 'login' %}">Login</a> to add comments</h3>
        {% endif %}

    </div>
</form>